# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Petsy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Petsy
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crash'
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireImage', '~> 3.1'
  pod 'PromiseKit'
  pod 'PromiseKit/CoreLocation', '~> 4.0'
  pod 'ReachabilitySwift', '~> 3'
  pod 'Koloda', '~> 4.3.1'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "GeoFire"
        target.build_configurations.each do |config|
          config.build_settings["FRAMEWORK_SEARCH_PATHS"] = '$(inherited) "${SRCROOT}/FirebaseDatabase/Frameworks"'
          config.build_settings["HEADER_SEARCH_PATHS"] = '$(inherited) "${PODS_ROOT}/Headers/Public/FirebaseDatabase"'
          config.build_settings["OTHER_CFLAGS"] = '$(inherited) -isystem "${PODS_ROOT}/Headers/Public/FirebaseDatabase"'
          config.build_settings["OTHER_LDFLAGS"] = '$(inherited) -framework "FirebaseDatabase"'
      end
    end

  end
end

  target 'PetsyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
